### ISSUE TITLE
Rejseplanen has changed their API

### ISSUE THREAD

**Issue by kp-bit** [DarkFox/rejseplanen-stog-card#14]
The integration is no longer pulling data as the old API is now closed. Information about the new API can be found here: https://labs.rejseplanen.dk/hc/en-us/articles/21554723926557-Om-API-2-0-nyt

Will this integration be updated to use the new API?

**Comment by DarkFox** [comment]
This is only a card that displays info from Rejseplanen. I am no longer involved in maintaining the integration.

Please refer to this issue on Home Assistant Core: https://github.com/home-assistant/core/issues/133420
